apiVersion: v1
kind: Pod
metadata:
  name: hostpath-app
  namespace: challenge3
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "echo Hello hostPath! > /mnt/data/challenge3-hostpath.log  && sleep 3600"]
    volumeMounts:
    - mountPath: "/mnt/data"
      name: hostpath-volume
  volumes:
  - name: hostpath-volume
    persistentVolumeClaim:
      claimName: hostpath-pvc
