apiVersion: v1
kind: Pod
metadata:
  name: verify-data-pod
  namespace: challenge4
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c", "while true; do cat /mnt/data/challenge4.txt; sleep 3600; done"]
    volumeMounts:
    - mountPath: /mnt/data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: restored-pvc
