apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-pvc
  namespace: challenge4
spec:
  dataSource:
    name: my-volumesnapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
