apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: challenge4
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
