apiVersion: v1
kind: Pod
metadata:
  name: write-data-pod
  namespace: challenge4
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    imagePullPolicy: Never
    command: ["/bin/sh", "-c", "echo 'Hello, Kubernetes!' > /mnt/data/hello.txt && sleep 3600"]
    volumeMounts:
    - mountPath: /mnt/data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: my-pvc
