apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-awesome-deployment
  namespace: challenge2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.36
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "while true; do echo $(date) $(hostname) healthy >> /mnt/data/challenge2.log; sleep 300; done"]
        volumeMounts:
        - name: data-volume
          mountPath: /mnt/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: my-pvc
  
