apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: challenge2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
